// <auto-generated />
using System;
using FilmCollection.DataAccess.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FilmCollection.DataAccess.Migrations
{
    [DbContext(typeof(FilmCollectionContext))]
    [Migration("20230616075454_InitializeDB")]
    partial class InitializeDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FilmCollection.DataAccess.Models.BaseFilmInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("AverageRating")
                        .HasColumnType("float");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<int>("NumberOfRatings")
                        .HasColumnType("int");

                    b.Property<string>("PosterURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AverageRating")
                        .HasFilter("[AverageRating] > 0");

                    b.HasIndex("NumberOfRatings")
                        .HasFilter("[NumberOfRatings] > 0");

                    b.HasIndex("ReleaseDate");

                    b.HasIndex("Title");

                    b.ToTable("BaseFilmInfo");
                });

            modelBuilder.Entity("FilmCollection.DataAccess.Models.Collection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("Collection");
                });

            modelBuilder.Entity("FilmCollection.DataAccess.Models.FilmCollection", b =>
                {
                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BaseFilmInfoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CollectionId", "BaseFilmInfoId");

                    b.HasIndex("BaseFilmInfoId");

                    b.ToTable("FilmCollection");
                });

            modelBuilder.Entity("FilmCollection.DataAccess.Models.FilmCountry", b =>
                {
                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<Guid>("BaseFilmInfoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CountryId", "BaseFilmInfoId");

                    b.HasIndex("BaseFilmInfoId");

                    b.ToTable("FilmCountry");
                });

            modelBuilder.Entity("FilmCollection.DataAccess.Models.FilmGenre", b =>
                {
                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BaseFilmInfoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GenreId", "BaseFilmInfoId");

                    b.HasIndex("BaseFilmInfoId");

                    b.ToTable("FilmGenre");
                });

            modelBuilder.Entity("FilmCollection.DataAccess.Models.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Genre");
                });

            modelBuilder.Entity("FilmCollection.DataAccess.Models.FilmCollection", b =>
                {
                    b.HasOne("FilmCollection.DataAccess.Models.BaseFilmInfo", "BaseFilmInfo")
                        .WithMany("FilmCollections")
                        .HasForeignKey("BaseFilmInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FilmCollection.DataAccess.Models.Collection", "Collection")
                        .WithMany("FilmCollections")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseFilmInfo");

                    b.Navigation("Collection");
                });

            modelBuilder.Entity("FilmCollection.DataAccess.Models.FilmCountry", b =>
                {
                    b.HasOne("FilmCollection.DataAccess.Models.BaseFilmInfo", "BaseFilmInfo")
                        .WithMany("FilmCountries")
                        .HasForeignKey("BaseFilmInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseFilmInfo");
                });

            modelBuilder.Entity("FilmCollection.DataAccess.Models.FilmGenre", b =>
                {
                    b.HasOne("FilmCollection.DataAccess.Models.BaseFilmInfo", "BaseFilmInfo")
                        .WithMany("FilmGenres")
                        .HasForeignKey("BaseFilmInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FilmCollection.DataAccess.Models.Genre", "Genre")
                        .WithMany("FilmGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseFilmInfo");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("FilmCollection.DataAccess.Models.BaseFilmInfo", b =>
                {
                    b.Navigation("FilmCollections");

                    b.Navigation("FilmCountries");

                    b.Navigation("FilmGenres");
                });

            modelBuilder.Entity("FilmCollection.DataAccess.Models.Collection", b =>
                {
                    b.Navigation("FilmCollections");
                });

            modelBuilder.Entity("FilmCollection.DataAccess.Models.Genre", b =>
                {
                    b.Navigation("FilmGenres");
                });
#pragma warning restore 612, 618
        }
    }
}
