version: '3.4'

services:
    rabbitmq:
        container_name: RabbitMQ
        image: rabbitmq:3-management-alpine
        ports:
          - 5672:5672
          - 15672:15672
        restart: unless-stopped

    sqlserver: 
        container_name: SqlServer
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
          - 1433:1433
        environment:
          - ACCEPT_EULA=Y
          - MSSQL_SA_PASSWORD=Passw0rd
        restart: unless-stopped

    rating:
        container_name: Rating
        build:
          context: "."
          dockerfile: /Services/Rating/Rating.WebAPI/Dockerfile
        depends_on:
          - sqlserver
          - rabbitmq
        ports: 
         - 9001:80
        environment:
          - ASPNETCORE_ENVIRONMENT=Docker
        restart: unless-stopped

    reviews:
        container_name: Review
        build:
          context: "."
          dockerfile: /Services/Reviews/Reviews.API/Dockerfile
        depends_on:
          - sqlserver
          - rabbitmq
        ports: 
         - 8001:80
        environment:
          - ASPNETCORE_ENVIRONMENT=Docker
        restart: unless-stopped

    staff:
        container_name: Staff
        build:
          context: "."
          dockerfile: /Services/Staff/Staff.API/Dockerfile
        depends_on:
          - sqlserver
          - rabbitmq
        ports: 
         - 7001:80
        environment:
          - ASPNETCORE_ENVIRONMENT=Docker
        restart: unless-stopped

    film:
        container_name: Film
        build:
          context: "."
          dockerfile: /Services/Film/Film.API/Dockerfile
        depends_on:
          - sqlserver
          - rabbitmq
        ports: 
         - 6001:80
        environment:
          - ASPNETCORE_ENVIRONMENT=Docker
        restart: unless-stopped
  
    auth:
        container_name: Auth
        build:
          context: "."
          dockerfile: /Services/Authentication/Authentication.API/Dockerfile
        depends_on:
          - sqlserver
        ports: 
         - 5001:80
        environment:
          - ASPNETCORE_ENVIRONMENT=Docker
        restart: unless-stopped

    filmcollection:
        container_name: FilmCollection
        build:
            context: "."
            dockerfile: /Services/FilmCollection/FilmCollection.API/Dockerfile
        depends_on:
            - sqlserver
            - rabbitmq
        ports:
            - 4001:80
        environment:
            - ASPNETCORE_ENVIRONMENT=Docker
        restart: unless-stopped