version: '3.4'

services:

 sqlserver: 
    container_name: SqlServer
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Passw0rd
    restart: unless-stopped
 reviews:
    container_name: Review
    build:
      context: "."
      dockerfile: /Services/Reviews/Reviews.API/Dockerfile
    depends_on:
      - sqlserver
    ports: 
     - 9001:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    restart: unless-stopped